version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mein-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./backend/mosquitto:/mosquitto/config
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: chat_app_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: